# Generated by Django 4.1.4 on 2022-12-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Roll', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=20)),
                ('Physics', models.IntegerField()),
                ('C', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Drawing', models.IntegerField()),
                ('ES', models.IntegerField()),
            ],
        ),
    ]
